FROM php:8.0-apache

RUN docker-php-ext-install mysqli

RUN a2enmod rewrite

RUN sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

RUN sed -i 's/Require all denied/Require all granted/' /etc/apache2/apache2.conf